import sys as s


N1 = s.argv[1]
N2 = s.argv[2]
T = s.argv[3]
P = s.argv[4]
OUTNAME = 'run.nbs'




F = open(OUTNAME,'w')
F.write('#!/bin/bash \n')
F.write('#SBATCH -J ' + 'L-' + N1 + '-' + T + '\n')
F.write('#SBATCH -p "fe13" \n')
F.write('#SBATCH -N 1 \n')
F.write('#SBATCH -n 4 \n')
F.write('##SBATCH --ntasks-per-core=12 \n')
F.write('#SBATCH --time=96:00:00 \n')
F.write('#SBATCH -o slurm-%j.out \n')
F.write('#SBATCH -e slurm-%j.err \n')
F.write('#SBATCH --mail-type=END \n')
F.write('#SBATCH --mail-user=lan58@cornell.edu \n')
F.write('##SBATCH --use-hwthread-cpus \n')
F.write('\n')
F.write('### GET COMPUTE NODE NAME \n')
F.write("node_name=$(squeue -j $SLURM_JOB_ID| awk 'NR==2{print $8}') \n")
F.write('#node_name=$(squeue -h -o "%N" -j1000) \n')
F.write('echo $node_name \n')
F.write('\n')
F.write('##STORING /tmp/ directory PATH \n')
F.write('MYTMP=/tmp/$USER/$SLURM_JOB_ID \n')
F.write('\n')
F.write('##MAKING DIRECTORY IN COMPUTE /tmp/userid \n')
F.write('/usr/bin/mkdir -p $MYTMP || exit $? \n')
F.write('echo "Copy data to /tmp on the compute node." \n')
F.write('\n')
F.write('## copying files from working dir to compute node dir ## NOTE: DIRECTORY HAS BEEN EXCLUDED \n')
F.write('cp -rp $SLURM_SUBMIT_DIR/* $MYTMP || echo $? \n')
F.write('\n')
F.write('##cd to directory to run your job \n')
F.write('### SETTING UP nohup HERE \n')
F.write('\n')
F.write('#module load python \n')
F.write('echo " SETTING up Python code here" \n')
F.write('\n')
F.write('#echo " SETTING up Python code here" \n')
F.write('\n')
F.write('python ~/COPYTEST/run_copy.py $node_name $MYTMP $SLURM_SUBMIT_DIR \n')
F.write('\n')
F.write('#~/COPYTEST \n')
F.write('##nohup python -u ~/COPYPYTHON/run_copy.py $node_name $MYTMP $SLURM_SUBMIT_DIR > /dev/null & \n')
F.write('\n')
F.write('echo "copy python code setup is complete" \n')
F.write('\n')
F.write('##cd to directory to run your job \n')
F.write('cd $MYTMP \n')
F.write('\n')
F.write('echo "Running EXECUTABLE HERE" \n')
F.write('\n')
F.write('mpirun -np $SLURM_NTASKS /home/fs01/lan58/recovery/software/lammps-3Mar20/build0/lmp_mpi -in PNP.in -log log.lammps > output -screen none -var N1 ' + N1 + ' -var N2 ' + N2 + ' -var T ' + T + ' -var P ' + P + ' \n')
F.write('\n')
F.write('echo "Ended at `date` on `hostname`." \n')
F.write('echo "Copy data back to $HOME." \n')
F.write('cp -rp $MYTMP/* $SLURM_SUBMIT_DIR || exit $? \n')
F.write('\n')
F.write('##DELETE FOLDER in compute node \n')
F.write('rm -rf $MYTMP \n')
F.write('\n')
F.write('exit 0 \n')
F.write('\n')
F.close()
